#! /bin/sh


# picom
killall -q picom
while pgrep -u $UID -x picom > /dev/null; do sleep 1; done
picom &


# polybar 
#killall -q polybar
#while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
#polybar -r -c ~/.config/polybar/minimal min &


# keybinds
sxhkd &

# keyboard touchpad and wallpaper
sh $HOME/.config/autoexec/keyntouch.sh &
sh $HOME/.config/autoexec/wallpaper.sh &

# workspace count
bspc monitor -d I II III IV V

#border
bspc config border_width 0 
bspc config window_gap 12


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# focus follow mouse pointer
bspc config focus_follows_pointer true
#bspc rule -a Terminator state=floating
bspc rule -a dolphin state=floating
