call plug#begin('~/.vim/plugins')

" plugins "
Plug 'vim-airline/vim-airline'
Plug 'megantiu/true.vim'

call plug#end()


" enable 24bit true color
 if (has("termguicolors"))
   set termguicolors
 endif

 " enable the theme
 syntax enable
 colorscheme true

let g:true_airline = 1
let g:airline_theme='true'


set number

set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set encoding=utf-8
